import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Next JS Algorithms</h1>
        <div className={styles.card}>
          <div className={styles.title}>
            <Link href="/factorial">
              <a>Factorial</a>
            </Link>
          </div>
          <div className={styles.title}>
            <Link href="/fibonacci">
              <a>Fibonacci</a>
            </Link>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
