import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Next JS Algorithms</h1>
        {/* div with titles */}
        <div className={styles.grid}>
          <div className={styles.card}>
            {/* link to factorial page */}
            <div className={styles.title}>
              <a href="/factorial" className={styles.link}>
                factorial
              </a>
              <br />
              <a href="/fibonacci" className={styles.link}>
                fibonacci
              </a>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
